from fpdf import FPDF
from datetime import datetime
import os

REPORT_DIR = r"C:\Users\91877\Desktop\stock bot"
PRIMARY    = (30, 58, 95)
GREEN      = (22, 163, 74)
RED        = (220, 38, 38)
LIGHT_GRAY = (248, 250, 252)
MID_GRAY   = (100, 116, 139)
WHITE      = (255, 255, 255)
BORDER     = (226, 232, 240)


class PDF(FPDF):
    def header(self):
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*MID_GRAY)
        self.cell(0, 10, f"Auto-generated by Stock Bot  |  Paper Trading  |  bensammanuel@gmail.com  |  Page {self.page_no()}", align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*MID_GRAY)
        self.set_fill_color(*LIGHT_GRAY)
        self.cell(0, 7, f"  {title.upper()}", ln=True, fill=True)
        self.ln(2)

    def colored_cell(self, w, h, txt, value=None, bold=False):
        if value is not None:
            self.set_text_color(*(GREEN if value >= 0 else RED))
        if bold:
            self.set_font("Helvetica", "B", 9)
        self.cell(w, h, txt, align="R")
        self.set_text_color(30, 30, 30)
        self.set_font("Helvetica", "", 9)


def _sign(v):
    return "+" if v >= 0 else ""


def generate_trade_pdf(portfolio, position_details, trades, live_value):
    os.makedirs(REPORT_DIR, exist_ok=True)
    now       = datetime.now()
    date_str  = now.strftime("%d %B %Y")
    file_date = now.strftime("%Y-%m-%d")

    initial      = portfolio["initial_capital"]
    total_profit = round(portfolio["total_profit"], 2)
    growth_pct   = round(((live_value - initial) / initial) * 100, 2)
    winning      = [t for t in trades if t["profit"] > 0]
    win_rate     = round((len(winning) / len(trades)) * 100, 1) if trades else 0

    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(15, 15, 15)

    # ── Header ──────────────────────────────────────────────
    pdf.set_fill_color(*PRIMARY)
    pdf.rect(0, 0, 210, 38, "F")
    pdf.set_xy(15, 8)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(147, 197, 253)
    pdf.cell(0, 6, "PAPER TRADING BOT", ln=True)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*WHITE)
    pdf.cell(0, 10, "Daily Trade Report", ln=True)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(191, 219, 254)
    pdf.cell(0, 6, f"{date_str}  |  Generated at {now.strftime('%I:%M %p')}", ln=True)
    pdf.ln(12)

    # ── Stat Cards ──────────────────────────────────────────
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*MID_GRAY)
    cards = [
        ("Starting Capital", f"Rs.{initial:,.0f}", None),
        ("Current Value",    f"Rs.{live_value:,.0f}", None),
        ("Total P&L",        f"{_sign(total_profit)}Rs.{abs(total_profit):,.2f}", total_profit),
        ("Growth",           f"{_sign(growth_pct)}{growth_pct}%", growth_pct),
        ("Win Rate",         f"{win_rate}%", win_rate - 50),
    ]
    cw = 36
    for label, val, indicator in cards:
        pdf.set_fill_color(*LIGHT_GRAY)
        pdf.set_draw_color(*BORDER)
        x = pdf.get_x()
        y = pdf.get_y()
        pdf.rect(x, y, cw, 18, "FD")
        pdf.set_xy(x + 2, y + 2)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*MID_GRAY)
        pdf.cell(cw - 4, 5, label.upper(), ln=True)
        pdf.set_x(x + 2)
        if indicator is not None:
            pdf.set_text_color(*(GREEN if indicator >= 0 else RED))
        else:
            pdf.set_text_color(*PRIMARY)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(cw - 4, 8, val, ln=False)
        pdf.set_xy(x + cw, y)
    pdf.ln(22)

    # ── Open Positions ───────────────────────────────────────
    pdf.section_title("Open Positions")
    if position_details:
        headers = ["Stock", "Buy Date", "Buy Price", "Cur Price", "Shares", "Invested", "Unrealised P&L"]
        widths  = [28, 24, 26, 26, 18, 26, 32]
        pdf.set_fill_color(*PRIMARY)
        pdf.set_text_color(*WHITE)
        pdf.set_font("Helvetica", "B", 8)
        for h, w in zip(headers, widths):
            pdf.cell(w, 7, h, align="C", fill=True)
        pdf.ln()
        pdf.set_font("Helvetica", "", 9)
        for i, (sym, p) in enumerate(position_details.items()):
            pdf.set_fill_color(*(LIGHT_GRAY if i % 2 == 0 else WHITE))
            pdf.set_text_color(30, 30, 30)
            pdf.cell(widths[0], 7, sym.replace(".NS", ""), fill=True)
            pdf.cell(widths[1], 7, p["buy_date"], align="C", fill=True)
            pdf.cell(widths[2], 7, f"Rs.{p['buy_price']:,.2f}", align="R", fill=True)
            pdf.cell(widths[3], 7, f"Rs.{p['current_price']:,.2f}", align="R", fill=True)
            pdf.cell(widths[4], 7, str(p["shares"]), align="C", fill=True)
            pdf.cell(widths[5], 7, f"Rs.{p['cost']:,.2f}", align="R", fill=True)
            sign = _sign(p["pnl"])
            pdf.set_text_color(*(GREEN if p["pnl"] >= 0 else RED))
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(widths[6], 7, f"{sign}Rs.{p['pnl']} ({sign}{p['pnl_pct']}%)", align="R", fill=True)
            pdf.set_font("Helvetica", "", 9)
            pdf.ln()
    else:
        pdf.set_text_color(*MID_GRAY)
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 8, "  No open positions today.", ln=True)
    pdf.ln(4)

    # ── Closed Trades ────────────────────────────────────────
    pdf.section_title("Closed Trade History")
    if trades:
        headers = ["#", "Stock", "Buy Date", "Sell Date", "Buy Price", "Sell Price", "P&L", "Exit"]
        widths  = [10, 25, 24, 24, 24, 24, 30, 27]
        pdf.set_fill_color(*PRIMARY)
        pdf.set_text_color(*WHITE)
        pdf.set_font("Helvetica", "B", 8)
        for h, w in zip(headers, widths):
            pdf.cell(w, 7, h, align="C", fill=True)
        pdf.ln()
        pdf.set_font("Helvetica", "", 9)
        for i, t in enumerate(trades, 1):
            pdf.set_fill_color(*(LIGHT_GRAY if i % 2 == 0 else WHITE))
            pdf.set_text_color(30, 30, 30)
            pdf.cell(widths[0], 7, str(i), align="C", fill=True)
            pdf.cell(widths[1], 7, t["symbol"].replace(".NS", ""), fill=True)
            pdf.cell(widths[2], 7, t["buy_date"], align="C", fill=True)
            pdf.cell(widths[3], 7, t["sell_date"], align="C", fill=True)
            pdf.cell(widths[4], 7, f"Rs.{t['buy_price']:,.2f}", align="R", fill=True)
            pdf.cell(widths[5], 7, f"Rs.{t['sell_price']:,.2f}", align="R", fill=True)
            sign = _sign(t["profit"])
            pdf.set_text_color(*(GREEN if t["profit"] >= 0 else RED))
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(widths[6], 7, f"{sign}Rs.{t['profit']} ({sign}{t['profit_pct']}%)", align="R", fill=True)
            pdf.set_text_color(*(GREEN if t["reason"] == "TARGET HIT" else RED))
            pdf.set_font("Helvetica", "", 8)
            pdf.cell(widths[7], 7, t["reason"], align="C", fill=True)
            pdf.set_font("Helvetica", "", 9)
            pdf.ln()

        pdf.ln(3)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*PRIMARY)
        pdf.cell(60, 7, f"Total Trades: {len(trades)}")
        pdf.cell(60, 7, f"Winning: {len(winning)}  |  Losing: {len(trades)-len(winning)}")
        pdf.cell(60, 7, f"Win Rate: {win_rate}%")
    else:
        pdf.set_text_color(*MID_GRAY)
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 8, "  No closed trades yet.", ln=True)

    path = os.path.join(REPORT_DIR, f"TradeReport_{file_date}.pdf")
    pdf.output(path)
    print(f"PDF saved: {path}", flush=True)
    return path


def generate_market_pdf(nifty, banknifty, sensex, gainers, losers, advances, declines, sentiment):
    os.makedirs(REPORT_DIR, exist_ok=True)
    now       = datetime.now()
    date_str  = now.strftime("%d %B %Y")
    file_date = now.strftime("%Y-%m-%d")

    sentiment_color = GREEN if sentiment == "BULLISH" else RED if sentiment == "BEARISH" else (217, 119, 6)

    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(15, 15, 15)

    # ── Header ──────────────────────────────────────────────
    pdf.set_fill_color(*PRIMARY)
    pdf.rect(0, 0, 210, 38, "F")
    pdf.set_xy(15, 8)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(147, 197, 253)
    pdf.cell(0, 6, "PAPER TRADING BOT", ln=True)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*WHITE)
    pdf.cell(0, 10, "Morning Market Report", ln=True)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(191, 219, 254)
    pdf.cell(0, 6, f"{date_str}  |  Generated at {now.strftime('%I:%M %p')}", ln=True)
    pdf.ln(12)

    # ── Sentiment Badge ──────────────────────────────────────
    pdf.set_fill_color(*sentiment_color)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(50, 8, f"  {sentiment}", fill=True, ln=False)
    pdf.set_text_color(*MID_GRAY)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 8, f"   Advances: {advances}  |  Declines: {declines}", ln=True)
    pdf.ln(4)

    # ── Indices ──────────────────────────────────────────────
    pdf.section_title("Market Indices")
    headers = ["Index", "Price", "Change", "% Change"]
    widths  = [50, 45, 45, 40]
    pdf.set_fill_color(*PRIMARY)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 9)
    for h, w in zip(headers, widths):
        pdf.cell(w, 7, h, align="C", fill=True)
    pdf.ln()
    pdf.set_font("Helvetica", "", 9)
    for i, idx in enumerate([nifty, banknifty, sensex]):
        if not idx:
            continue
        pdf.set_fill_color(*(LIGHT_GRAY if i % 2 == 0 else WHITE))
        pdf.set_text_color(30, 30, 30)
        pdf.cell(widths[0], 7, idx["name"], fill=True)
        pdf.cell(widths[1], 7, f"{idx['current']:,.2f}", align="R", fill=True)
        sign = _sign(idx["change"])
        pdf.set_text_color(*(GREEN if idx["change"] >= 0 else RED))
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(widths[2], 7, f"{sign}{idx['change']}", align="R", fill=True)
        pdf.cell(widths[3], 7, f"{sign}{idx['change_pct']}%", align="R", fill=True)
        pdf.set_font("Helvetica", "", 9)
        pdf.ln()
    pdf.ln(4)

    # ── Gainers & Losers ─────────────────────────────────────
    col_w = 88
    gx = 15
    lx = 15 + col_w + 4
    y  = pdf.get_y()

    for title, stocks, color, start_x in [
        ("Top 5 Gainers", gainers, GREEN, gx),
        ("Top 5 Losers",  losers,  RED,   lx),
    ]:
        pdf.set_xy(start_x, y)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*MID_GRAY)
        pdf.set_fill_color(*LIGHT_GRAY)
        pdf.cell(col_w, 7, f"  {title.upper()}", fill=True, ln=False)
        pdf.set_xy(start_x, y + 7)
        pdf.set_fill_color(*color)
        pdf.set_text_color(*WHITE)
        pdf.set_font("Helvetica", "B", 8)
        for h, w in [("Stock", 40), ("Price", 28), ("Change", 20)]:
            pdf.cell(w, 6, h, align="C", fill=True)
        pdf.set_xy(start_x, y + 13)
        for i, s in enumerate(stocks):
            pdf.set_xy(start_x, y + 13 + i * 7)
            pdf.set_fill_color(*(LIGHT_GRAY if i % 2 == 0 else WHITE))
            pdf.set_text_color(30, 30, 30)
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(40, 7, s["symbol"], fill=True)
            pdf.cell(28, 7, f"Rs.{s['price']:,.0f}", align="R", fill=True)
            sign = _sign(s["change_pct"])
            pdf.set_text_color(*color)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(20, 7, f"{sign}{s['change_pct']}%", align="R", fill=True)

    pdf.set_xy(15, y + 13 + 5 * 7 + 4)

    path = os.path.join(REPORT_DIR, f"MarketReport_{file_date}.pdf")
    pdf.output(path)
    print(f"PDF saved: {path}", flush=True)
    return path
