import json
import os
from datetime import datetime
import yfinance as yf
from notifier import send_email
from email_templates import trade_report_html
from pdf_report import generate_trade_pdf

PORTFOLIO_FILE = "portfolio.json"
REPORT_DIR = r"C:\Users\91877\Desktop\stock bot"


def get_current_price(symbol):
    try:
        df = yf.Ticker(symbol).history(period="1d", timeout=8)
        return round(df["Close"].iloc[-1], 2)
    except Exception:
        return None


def generate_report():
    os.makedirs(REPORT_DIR, exist_ok=True)

    if not os.path.exists(PORTFOLIO_FILE):
        print("No portfolio found. Bot has not run yet.")
        return

    with open(PORTFOLIO_FILE, "r") as f:
        portfolio = json.load(f)

    now = datetime.now()
    date_str = now.strftime("%d %B %Y")
    file_date = now.strftime("%Y-%m-%d")

    # --- Compute live portfolio value ---
    live_value = portfolio["cash"]
    position_details = {}
    for sym, pos in portfolio["positions"].items():
        cur = get_current_price(sym) or pos["buy_price"]
        cur_value = round(cur * pos["shares"], 2)
        pnl = round(cur_value - pos["cost"], 2)
        pnl_pct = round((pnl / pos["cost"]) * 100, 2)
        live_value += cur_value
        position_details[sym] = {**pos, "current_price": cur, "current_value": cur_value, "pnl": pnl, "pnl_pct": pnl_pct}

    initial = portfolio["initial_capital"]
    total_profit = round(portfolio["total_profit"], 2)
    growth_pct = round(((live_value - initial) / initial) * 100, 2)
    trades = portfolio["trades"]
    winning = [t for t in trades if t["profit"] > 0]
    losing  = [t for t in trades if t["profit"] <= 0]
    win_rate = round((len(winning) / len(trades)) * 100, 1) if trades else 0

    # --- Build report text ---
    sep  = "=" * 62
    dash = "-" * 62

    lines = [
        sep,
        "           STOCK BOT  —  DAILY TRADE REPORT",
        f"                    {date_str}",
        sep,
        "",
        "PORTFOLIO OVERVIEW",
        dash,
        f"  Starting Capital    :  Rs. {initial:>10,.2f}",
        f"  Current Cash        :  Rs. {portfolio['cash']:>10,.2f}",
        f"  Total Portfolio Value:  Rs. {live_value:>10,.2f}",
        f"  Realised Profit/Loss:  Rs. {total_profit:>10,.2f}",
        f"  Overall Growth      :  {growth_pct}%",
        "",
    ]

    # Open positions
    lines += ["OPEN POSITIONS", dash]
    if position_details:
        for sym, p in position_details.items():
            direction = "+" if p["pnl"] >= 0 else ""
            lines += [
                f"  Stock            : {sym}",
                f"  Buy Date         : {p['buy_date']}",
                f"  Buy Price        : Rs. {p['buy_price']}",
                f"  Current Price    : Rs. {p['current_price']}",
                f"  Shares Held      : {p['shares']}",
                f"  Amount Invested  : Rs. {p['cost']:,.2f}",
                f"  Current Value    : Rs. {p['current_value']:,.2f}",
                f"  Unrealised P&L   : Rs. {direction}{p['pnl']} ({direction}{p['pnl_pct']}%)",
                f"  Target Sell      : Rs. {round(p['buy_price'] * 1.10, 2)}  (+10%)",
                f"  Stop-Loss        : Rs. {round(p['buy_price'] * 0.95, 2)}  (-5%)",
                "",
            ]
    else:
        lines += ["  No open positions today.", ""]

    # Closed trade history
    lines += ["CLOSED TRADE HISTORY", dash]
    if trades:
        for i, t in enumerate(trades, 1):
            direction = "+" if t["profit"] >= 0 else ""
            lines += [
                f"  Trade #{i}",
                f"    Stock        : {t['symbol']}",
                f"    Buy Date     : {t['buy_date']}",
                f"    Sell Date    : {t['sell_date']}",
                f"    Buy Price    : Rs. {t['buy_price']}",
                f"    Sell Price   : Rs. {t['sell_price']}",
                f"    Shares       : {t['shares']}",
                f"    Profit/Loss  : Rs. {direction}{t['profit']} ({direction}{t['profit_pct']}%)",
                f"    Exit Reason  : {t['reason']}",
                "",
            ]
        lines += [
            f"  Total Trades   : {len(trades)}",
            f"  Winning Trades : {len(winning)}",
            f"  Losing Trades  : {len(losing)}",
            f"  Win Rate       : {win_rate}%",
            f"  Best Trade     : Rs. {max(t['profit'] for t in trades):,.2f}",
            f"  Worst Trade    : Rs. {min(t['profit'] for t in trades):,.2f}",
            "",
        ]
    else:
        lines += ["  No closed trades yet — positions still open or no buys made.", ""]

    lines += [
        sep,
        "     Report auto-generated by Stock Bot (Paper Trading)",
        f"     Generated on: {now.strftime('%d-%m-%Y at %I:%M %p')}",
        sep,
    ]

    report_text = "\n".join(lines)

    # Save to Desktop/stock bot/
    report_path = os.path.join(REPORT_DIR, f"Report_{file_date}.txt")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_text)
    print(f"Report saved: {report_path}", flush=True)

    # --- WhatsApp summary ---
    wa = [
        f"STOCK BOT REPORT - {date_str}",
        f"Capital: Rs.{initial:,.0f} -> Rs.{round(live_value,2):,.0f}",
        f"Growth: {growth_pct}%  |  P&L: Rs.{total_profit:,.2f}",
    ]
    if position_details:
        wa.append("\nOPEN POSITIONS:")
        for sym, p in position_details.items():
            wa.append(f"  {sym}: {p['shares']} shares @ Rs.{p['buy_price']} | Now Rs.{p['current_price']} ({'+' if p['pnl_pct']>=0 else ''}{p['pnl_pct']}%)")
    if trades:
        wa.append(f"\nCLOSED TRADES: {len(trades)} total | Win Rate: {win_rate}%")
        last = trades[-1]
        wa.append(f"Last Trade: {last['symbol']} {'+' if last['profit']>=0 else ''}{last['profit']} ({last['reason']})")
    else:
        wa.append("\nNo closed trades yet.")
    wa.append("\nFull report saved to Desktop > stock bot folder.")

    html     = trade_report_html(portfolio, position_details, trades, live_value)
    pdf_path = generate_trade_pdf(portfolio, position_details, trades, live_value)
    send_email(f"Stock Bot — Daily Trade Report {date_str}", "\n".join(wa), html=html, pdf_path=pdf_path)


if __name__ == "__main__":
    generate_report()
